// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZcFLHEVLEnr0pGCOzz2GliOhWop583YU',
    appId: '1:471086979502:web:3380fa0459505ccaead03f',
    messagingSenderId: '471086979502',
    projectId: 'neontown',
    authDomain: 'neontown.firebaseapp.com',
    storageBucket: 'neontown.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtJx3QnoTOVfOZO6eIi8y7MDZoH5heD5I',
    appId: '1:471086979502:android:67048b8ec462a470ead03f',
    messagingSenderId: '471086979502',
    projectId: 'neontown',
    storageBucket: 'neontown.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5fHGByNs7dxZcTsAlFtLDhC4gEB6hfQc',
    appId: '1:471086979502:ios:dc7e47d39c0ea79fead03f',
    messagingSenderId: '471086979502',
    projectId: 'neontown',
    storageBucket: 'neontown.firebasestorage.app',
    iosBundleId: 'com.neontown.app',
  );
}
